using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

#pragma warning disable RSEXPERIMENTAL002

namespace WitnessSharp.Analyzers;

[Generator]
public sealed class LoggerMessageInterceptorGenerator : IIncrementalGenerator
{
    private const string GeneratedNamespace = "WitnessSharp.Generated";
    private const string GeneratedClassName = "LoggerMessageInterceptors";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidateMethods = context.SyntaxProvider
            .CreateSyntaxProvider<ExtensionLoggingMethodCandidate?>(
                static (node, _) => node is MethodDeclarationSyntax method && method.ParameterList.Parameters.Count > 0,
                static (syntaxContext, cancellationToken) => TryCreateCandidate(syntaxContext, cancellationToken, out var candidate) ? candidate : null)
            .Where(static candidate => candidate.HasValue)
            .Select(static (candidate, _) => candidate.Value);

        var callSites = context.SyntaxProvider
            .CreateSyntaxProvider<InterceptedCallSite?>(
                static (node, _) => node is InvocationExpressionSyntax,
                static (syntaxContext, cancellationToken) => TryCreateCallSite(syntaxContext, cancellationToken, out var callSite) ? callSite : null)
            .Where(static callSite => callSite.HasValue)
            .Select(static (callSite, _) => callSite.Value);

        var generatorOptions = context.AnalyzerConfigOptionsProvider
            .Select(static (provider, _) => GeneratorOptions.Create(provider));

        var compilationInfo = context.CompilationProvider
            .Select(static (compilation, _) => CompilationInfo.Create(compilation));

        var generationInput = candidateMethods
            .Collect()
            .Combine(callSites.Collect())
            .Combine(generatorOptions)
            .Combine(compilationInfo);

        context.RegisterSourceOutput(generationInput, static (productionContext, input) =>
        {
            var candidates = input.Left.Left.Left;
            var callSites = input.Left.Left.Right;
            var options = input.Left.Right;
            var compilationInfo = input.Right;
            Emit(productionContext, candidates, callSites, options, compilationInfo);
        });
    }

    private static void Emit(
        SourceProductionContext context,
        ImmutableArray<ExtensionLoggingMethodCandidate> candidates,
        ImmutableArray<InterceptedCallSite> callSites,
        GeneratorOptions options,
        CompilationInfo compilationInfo)
    {
        if (candidates.IsDefaultOrEmpty || !options.IsTargetFrameworkSupported(compilationInfo) || !options.IsInterceptorNamespaceEnabled(GeneratedNamespace))
        {
            return;
        }

        var distinctCandidates = candidates
            .GroupBy(static candidate => candidate.MethodKey, StringComparer.Ordinal)
            .Select(static group => group.First())
            .OrderBy(static candidate => candidate.MethodKey, StringComparer.Ordinal)
            .ToArray();

        if (distinctCandidates.Length == 0)
        {
            return;
        }

        var callSitesByMethod = callSites
            .GroupBy(static callSite => callSite.MethodKey, StringComparer.Ordinal)
            .ToDictionary(
                static group => group.Key,
                static group => group
                    .GroupBy(static callSite => callSite.Data, StringComparer.Ordinal)
                    .Select(static duplicateGroup => duplicateGroup.First())
                    .OrderBy(static callSite => callSite.Data, StringComparer.Ordinal)
                    .ToArray(),
                StringComparer.Ordinal);

        var emittedCandidates = distinctCandidates
            .Where(candidate => callSitesByMethod.ContainsKey(candidate.MethodKey))
            .ToArray();

        if (emittedCandidates.Length == 0)
        {
            return;
        }

        context.AddSource("InterceptsLocationAttribute.g.cs", GetInterceptsLocationAttributeSource());

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable");
        builder.AppendLine($"namespace {GeneratedNamespace};");
        builder.AppendLine();
        builder.AppendLine($"file static partial class {GeneratedClassName}");
        builder.AppendLine("{");

        for (var index = 0; index < emittedCandidates.Length; index++)
        {
            var candidate = emittedCandidates[index];
            var candidateCallSites = callSitesByMethod[candidate.MethodKey];
            AppendCandidate(builder, candidate, candidateCallSites, index);
        }

        builder.AppendLine("}");
        context.AddSource("LoggerMessageInterceptors.g.cs", builder.ToString());
    }

    private static string GetInterceptsLocationAttributeSource()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable");
        builder.AppendLine("namespace System.Runtime.CompilerServices");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        builder.AppendLine("    internal sealed class InterceptsLocationAttribute : global::System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("        public InterceptsLocationAttribute(int version, string data)");
        builder.AppendLine("        {");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendCandidate(
        StringBuilder builder,
        ExtensionLoggingMethodCandidate candidate,
        IReadOnlyList<InterceptedCallSite> callSites,
        int index)
    {
        var interceptorMethodName = $"Intercept_{index.ToString(CultureInfo.InvariantCulture)}";
        var loggerMessageMethodName = $"Log_{index.ToString(CultureInfo.InvariantCulture)}";

        foreach (var callSite in callSites)
        {
            builder.Append("    [global::System.Runtime.CompilerServices.InterceptsLocation(")
                .Append(callSite.Version.ToString(CultureInfo.InvariantCulture))
                .Append(", ")
                .Append(EscapeStringLiteral(callSite.Data))
                .AppendLine(")]");
        }

        builder.Append("    public static void ")
            .Append(interceptorMethodName)
            .Append('(');
        AppendSignatureParameters(builder, candidate.OriginalMethodParameters);
        builder.AppendLine(")");
        builder.AppendLine("    {");
        builder.Append("        ")
            .Append(loggerMessageMethodName)
            .Append('(')
            .Append(candidate.WitnessParameterName)
            .Append(".Logger");

        if (candidate.ExceptionArgument is not null)
        {
            var exceptionArgument = candidate.ExceptionArgument.Value;
            builder.Append(", ").Append(exceptionArgument.ExpressionText);
        }

        foreach (var argument in candidate.ValueArguments)
        {
            builder.Append(", ").Append(argument.ExpressionText);
        }

        builder.AppendLine(");");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.Append("    [global::Microsoft.Extensions.Logging.LoggerMessage(Level = ")
            .Append(candidate.LogLevelExpression)
            .Append(", Message = ")
            .Append(EscapeStringLiteral(candidate.MessageTemplate))
            .AppendLine(")]");
        builder.Append("    static partial void ")
            .Append(loggerMessageMethodName)
            .Append("(global::Microsoft.Extensions.Logging.ILogger logger");

        if (candidate.ExceptionArgument is not null)
        {
            var exceptionArgument = candidate.ExceptionArgument.Value;
            builder.Append(", ")
                .Append(exceptionArgument.TypeName)
                .Append(' ')
                .Append(exceptionArgument.ParameterName);
        }

        foreach (var argument in candidate.ValueArguments)
        {
            builder.Append(", ")
                .Append(argument.TypeName)
                .Append(' ')
                .Append(argument.ParameterName);
        }

        builder.AppendLine(");");
        builder.AppendLine();
    }

    private static void AppendSignatureParameters(StringBuilder builder, ImmutableArray<InterceptorParameter> parameters)
    {
        for (var index = 0; index < parameters.Length; index++)
        {
            if (index > 0)
            {
                builder.Append(", ");
            }

            var parameter = parameters[index];
            if (parameter.IsThis)
            {
                builder.Append("this ");
            }

            AppendRefKind(builder, parameter.RefKind);
            if (parameter.IsParams)
            {
                builder.Append("params ");
            }

            builder.Append(parameter.TypeName)
                .Append(' ')
                .Append(parameter.Name);
        }
    }

    private static void AppendRefKind(StringBuilder builder, RefKind refKind)
    {
        switch (refKind)
        {
            case RefKind.Ref:
                builder.Append("ref ");
                break;
            case RefKind.Out:
                builder.Append("out ");
                break;
            case RefKind.In:
                builder.Append("in ");
                break;
        }
    }

    private static string EscapeStringLiteral(string value) => SymbolDisplay.FormatLiteral(value, quote: true);

    private static bool TryCreateCandidate(GeneratorSyntaxContext context, System.Threading.CancellationToken cancellationToken, out ExtensionLoggingMethodCandidate candidate)
    {
        candidate = default;

        var methodDeclaration = (MethodDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(methodDeclaration, cancellationToken) is not IMethodSymbol methodSymbol ||
            !methodSymbol.IsStatic ||
            !methodSymbol.IsExtensionMethod ||
            !methodSymbol.ReturnsVoid ||
            methodSymbol.TypeParameters.Length > 0)
        {
            return false;
        }

        var witnessParameter = methodSymbol.Parameters.FirstOrDefault();
        if (witnessParameter is null || !LoggerAnalysisHelpers.IsWitnessType(witnessParameter.Type))
        {
            return false;
        }

        if (!TryGetSingleInvocation(methodDeclaration, out var invocation) ||
            !TryCreateLoggedInvocation(context.SemanticModel, invocation, witnessParameter, methodSymbol.Parameters, cancellationToken, out var loggedInvocation))
        {
            return false;
        }

        var parameters = methodSymbol.Parameters
            .Select((parameter, index) => new InterceptorParameter(
                parameter.Name,
                GetTypeDisplayString(parameter.Type),
                parameter.RefKind,
                index == 0,
                parameter.IsParams))
            .ToImmutableArray();

        candidate = new ExtensionLoggingMethodCandidate(
            CreateMethodKey(methodSymbol),
            witnessParameter.Name,
            parameters,
            loggedInvocation.LogLevelExpression,
            loggedInvocation.MessageTemplate,
            loggedInvocation.ExceptionArgument,
            loggedInvocation.ValueArguments);
        return true;
    }

    private static bool TryCreateCallSite(GeneratorSyntaxContext context, System.Threading.CancellationToken cancellationToken, out InterceptedCallSite callSite)
    {
        callSite = default;

        var invocation = (InvocationExpressionSyntax)context.Node;
        var methodSymbol = LoggerAnalysisHelpers.GetInvokedMethod(context.SemanticModel, invocation, cancellationToken);
        if (methodSymbol is null)
        {
            return false;
        }

        var resolvedMethod = methodSymbol.ReducedFrom ?? methodSymbol;
        if (!resolvedMethod.IsExtensionMethod)
        {
            return false;
        }

        InterceptableLocation? interceptableLocation;
        try
        {
            interceptableLocation = context.SemanticModel.GetInterceptableLocation(invocation, cancellationToken);
        }
        catch (InvalidOperationException)
        {
            return false;
        }

        if (interceptableLocation is null)
        {
            return false;
        }

        callSite = new InterceptedCallSite(
            CreateMethodKey(resolvedMethod),
            interceptableLocation.Version,
            interceptableLocation.Data);
        return true;
    }

    private static bool TryGetSingleInvocation(MethodDeclarationSyntax methodDeclaration, out InvocationExpressionSyntax invocation)
    {
        invocation = null!;

        if (methodDeclaration.ExpressionBody?.Expression is InvocationExpressionSyntax expressionBodyInvocation)
        {
            invocation = expressionBodyInvocation;
            return true;
        }

        if (methodDeclaration.Body is not { Statements.Count: 1 })
        {
            return false;
        }

        if (methodDeclaration.Body.Statements[0] is ExpressionStatementSyntax { Expression: InvocationExpressionSyntax blockInvocation })
        {
            invocation = blockInvocation;
            return true;
        }

        return false;
    }

    private static bool TryCreateLoggedInvocation(
        SemanticModel semanticModel,
        InvocationExpressionSyntax invocation,
        IParameterSymbol witnessParameter,
        ImmutableArray<IParameterSymbol> methodParameters,
        System.Threading.CancellationToken cancellationToken,
        out LoggedInvocation loggedInvocation)
    {
        loggedInvocation = default;

        if (invocation.Expression is not MemberAccessExpressionSyntax methodAccess ||
            methodAccess.Expression is not MemberAccessExpressionSyntax loggerAccess ||
            loggerAccess.Name.Identifier.ValueText != LoggerAnalysisHelpers.LoggerPropertyName)
        {
            return false;
        }

        var methodSymbol = LoggerAnalysisHelpers.GetInvokedMethod(semanticModel, invocation, cancellationToken);
        if (methodSymbol is null || !LoggerAnalysisHelpers.IsSupportedLoggerMethod(methodSymbol))
        {
            return false;
        }

        var witnessReceiverSymbol = semanticModel.GetSymbolInfo(loggerAccess.Expression, cancellationToken).Symbol;
        if (!SymbolEqualityComparer.Default.Equals(witnessReceiverSymbol, witnessParameter))
        {
            return false;
        }

        var loggerProperty = semanticModel.GetSymbolInfo(loggerAccess.Name, cancellationToken).Symbol as IPropertySymbol;
        if (loggerProperty is null ||
            loggerProperty.Name != LoggerAnalysisHelpers.LoggerPropertyName ||
            !LoggerAnalysisHelpers.IsLoggerType(loggerProperty.Type))
        {
            return false;
        }

        var arguments = invocation.ArgumentList.Arguments;
        if (!TryGetLogLevelExpression(semanticModel, methodSymbol, arguments, cancellationToken, out var logLevelExpression, out var searchStartIndex) ||
            !TryFindMessageTemplate(semanticModel, arguments, searchStartIndex, cancellationToken, out var templateIndex, out var template))
        {
            return false;
        }

        var prefixArguments = arguments.Skip(searchStartIndex).Take(templateIndex - searchStartIndex).ToImmutableArray();
        var exceptionArguments = prefixArguments
            .Where(argument => IsExceptionType(semanticModel.GetTypeInfo(argument.Expression, cancellationToken).ConvertedType ?? semanticModel.GetTypeInfo(argument.Expression, cancellationToken).Type))
            .ToImmutableArray();
        if (prefixArguments.Length != exceptionArguments.Length || exceptionArguments.Length > 1)
        {
            return false;
        }

        var valueArguments = arguments.Skip(templateIndex + 1).ToImmutableArray();
        var placeholderNames = ExtractPlaceholders(template);
        if (placeholderNames.Count != valueArguments.Length)
        {
            return false;
        }

        var methodParameterNames = new HashSet<string>(methodParameters.Select(static parameter => parameter.Name), StringComparer.Ordinal);
        var usedGeneratedNames = new HashSet<string>(StringComparer.Ordinal) { "logger", "exception" };

        GeneratedLogArgument? exceptionArgument = null;
        if (exceptionArguments.Length == 1)
        {
            if (!TryCreateGeneratedArgument(
                    semanticModel,
                    exceptionArguments[0].Expression,
                    methodParameterNames,
                    "exception",
                    0,
                    usedGeneratedNames,
                    cancellationToken,
                    out var generatedExceptionArgument))
            {
                return false;
            }

            exceptionArgument = new GeneratedLogArgument(exceptionArguments[0].Expression.WithoutTrivia().ToString(), generatedExceptionArgument.TypeName, "exception");
        }

        var generatedArguments = ImmutableArray.CreateBuilder<GeneratedLogArgument>(valueArguments.Length);
        for (var index = 0; index < valueArguments.Length; index++)
        {
            if (!TryCreateGeneratedArgument(
                    semanticModel,
                    valueArguments[index].Expression,
                    methodParameterNames,
                    placeholderNames[index],
                    index + 1,
                    usedGeneratedNames,
                    cancellationToken,
                    out var generatedArgument))
            {
                return false;
            }

            generatedArguments.Add(generatedArgument);
        }

        loggedInvocation = new LoggedInvocation(logLevelExpression, template, exceptionArgument, generatedArguments.ToImmutable());
        return true;
    }

    private static bool TryCreateGeneratedArgument(
        SemanticModel semanticModel,
        ExpressionSyntax expression,
        ISet<string> methodParameterNames,
        string placeholderName,
        int index,
        ISet<string> usedGeneratedNames,
        System.Threading.CancellationToken cancellationToken,
        out GeneratedLogArgument generatedArgument)
    {
        generatedArgument = default;

        if (!IsSupportedGeneratedExpression(expression, semanticModel, methodParameterNames, cancellationToken))
        {
            return false;
        }

        var typeInfo = semanticModel.GetTypeInfo(expression, cancellationToken);
        var typeSymbol = typeInfo.Type ?? typeInfo.ConvertedType;
        if (typeSymbol is null || typeSymbol.TypeKind == TypeKind.Error || typeSymbol.IsAnonymousType)
        {
            return false;
        }

        var parameterName = CreateParameterName(expression, placeholderName, usedGeneratedNames, index);
        generatedArgument = new GeneratedLogArgument(expression.WithoutTrivia().ToString(), GetTypeDisplayString(typeSymbol), parameterName);
        return true;
    }

    private static bool IsSupportedGeneratedExpression(
        ExpressionSyntax expression,
        SemanticModel semanticModel,
        ISet<string> methodParameterNames,
        System.Threading.CancellationToken cancellationToken)
    {
        switch (expression)
        {
            case LiteralExpressionSyntax:
            case ThisExpressionSyntax:
            case BaseExpressionSyntax:
                return false;
            case IdentifierNameSyntax identifier:
                return semanticModel.GetSymbolInfo(identifier, cancellationToken).Symbol is IParameterSymbol parameter && methodParameterNames.Contains(parameter.Name);
            case MemberAccessExpressionSyntax memberAccess:
                return IsSupportedGeneratedExpression(memberAccess.Expression, semanticModel, methodParameterNames, cancellationToken);
            case ParenthesizedExpressionSyntax parenthesizedExpression:
                return IsSupportedGeneratedExpression(parenthesizedExpression.Expression, semanticModel, methodParameterNames, cancellationToken);
            case CastExpressionSyntax castExpression:
                return IsSupportedGeneratedExpression(castExpression.Expression, semanticModel, methodParameterNames, cancellationToken);
            case PrefixUnaryExpressionSyntax prefixUnaryExpression:
                return IsSupportedGeneratedExpression(prefixUnaryExpression.Operand, semanticModel, methodParameterNames, cancellationToken);
            case PostfixUnaryExpressionSyntax postfixUnaryExpression:
                return IsSupportedGeneratedExpression(postfixUnaryExpression.Operand, semanticModel, methodParameterNames, cancellationToken);
            case BinaryExpressionSyntax binaryExpression:
                return IsSupportedGeneratedExpression(binaryExpression.Left, semanticModel, methodParameterNames, cancellationToken)
                    && IsSupportedGeneratedExpression(binaryExpression.Right, semanticModel, methodParameterNames, cancellationToken);
            default:
                return false;
        }
    }

    private static bool TryGetLogLevelExpression(
        SemanticModel semanticModel,
        IMethodSymbol methodSymbol,
        SeparatedSyntaxList<ArgumentSyntax> arguments,
        System.Threading.CancellationToken cancellationToken,
        out string logLevelExpression,
        out int searchStartIndex)
    {
        searchStartIndex = 0;
        if (methodSymbol.Name != "Log")
        {
            logLevelExpression = methodSymbol.Name switch
            {
                "LogTrace" => "global::Microsoft.Extensions.Logging.LogLevel.Trace",
                "LogDebug" => "global::Microsoft.Extensions.Logging.LogLevel.Debug",
                "LogInformation" => "global::Microsoft.Extensions.Logging.LogLevel.Information",
                "LogWarning" => "global::Microsoft.Extensions.Logging.LogLevel.Warning",
                "LogError" => "global::Microsoft.Extensions.Logging.LogLevel.Error",
                "LogCritical" => "global::Microsoft.Extensions.Logging.LogLevel.Critical",
                _ => string.Empty,
            };

            return logLevelExpression.Length > 0;
        }

        if (arguments.Count == 0)
        {
            logLevelExpression = string.Empty;
            return false;
        }

        var levelSymbol = semanticModel.GetSymbolInfo(arguments[0].Expression, cancellationToken).Symbol as IFieldSymbol;
        if (levelSymbol?.ContainingType is not { Name: "LogLevel" } levelType || levelType.ContainingNamespace.ToDisplayString() != "Microsoft.Extensions.Logging")
        {
            logLevelExpression = string.Empty;
            return false;
        }

        logLevelExpression = levelSymbol.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "." + levelSymbol.Name;
        searchStartIndex = 1;
        return true;
    }

    private static bool TryFindMessageTemplate(
        SemanticModel semanticModel,
        SeparatedSyntaxList<ArgumentSyntax> arguments,
        int startIndex,
        System.Threading.CancellationToken cancellationToken,
        out int templateIndex,
        out string template)
    {
        templateIndex = -1;
        template = string.Empty;

        for (var index = startIndex; index < arguments.Count; index++)
        {
            var constantValue = semanticModel.GetConstantValue(arguments[index].Expression, cancellationToken);
            if (constantValue.HasValue && constantValue.Value is string templateValue)
            {
                templateIndex = index;
                template = templateValue;
                return true;
            }
        }

        return false;
    }

    private static bool IsExceptionType(ITypeSymbol? typeSymbol)
    {
        while (typeSymbol is not null)
        {
            if (typeSymbol.Name == nameof(Exception) && typeSymbol.ContainingNamespace.ToDisplayString() == nameof(System))
            {
                return true;
            }

            typeSymbol = (typeSymbol as INamedTypeSymbol)?.BaseType;
        }

        return false;
    }

    private static string CreateMethodKey(IMethodSymbol methodSymbol) =>
        methodSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string GetTypeDisplayString(ITypeSymbol typeSymbol) =>
        typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static List<string> ExtractPlaceholders(string template)
    {
        var placeholders = new List<string>();
        for (var index = 0; index < template.Length; index++)
        {
            if (template[index] != '{')
            {
                continue;
            }

            if (index + 1 < template.Length && template[index + 1] == '{')
            {
                index++;
                continue;
            }

            var endIndex = template.IndexOf('}', index + 1);
            if (endIndex < 0)
            {
                break;
            }

            var token = template.Substring(index + 1, endIndex - index - 1).Trim();
            if (token.Length > 0 && (token[0] == '@' || token[0] == '$'))
            {
                token = token.Substring(1);
            }

            var delimiterIndex = token.IndexOfAny(new[] { ',', ':' });
            if (delimiterIndex >= 0)
            {
                token = token.Substring(0, delimiterIndex);
            }

            if (token.Length > 0)
            {
                placeholders.Add(token);
            }

            index = endIndex;
        }

        return placeholders;
    }

    private static string CreateParameterName(ExpressionSyntax expression, string placeholderName, ISet<string> usedNames, int index)
    {
        var baseName = expression is IdentifierNameSyntax identifier
            ? SanitizeIdentifier(identifier.Identifier.ValueText)
            : ToCamelCase(SanitizeIdentifier(placeholderName));

        if (string.IsNullOrEmpty(baseName))
        {
            baseName = "arg" + index.ToString(CultureInfo.InvariantCulture);
        }

        var candidate = baseName;
        var suffix = 1;
        while (!usedNames.Add(candidate))
        {
            candidate = baseName + suffix.ToString(CultureInfo.InvariantCulture);
            suffix++;
        }

        return candidate;
    }

    private static string SanitizeIdentifier(string value)
    {
        var builder = new StringBuilder();
        foreach (var character in value)
        {
            if (builder.Length == 0)
            {
                if (SyntaxFacts.IsIdentifierStartCharacter(character))
                {
                    builder.Append(character);
                }
                else if (SyntaxFacts.IsIdentifierPartCharacter(character))
                {
                    builder.Append('_');
                    builder.Append(character);
                }
            }
            else if (SyntaxFacts.IsIdentifierPartCharacter(character))
            {
                builder.Append(character);
            }
        }

        return builder.ToString();
    }

    private static string ToCamelCase(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return value;
        }

        return value.Length == 1
            ? char.ToLowerInvariant(value[0]).ToString()
            : char.ToLowerInvariant(value[0]) + value.Substring(1);
    }

    private readonly struct CompilationInfo
    {
        public CompilationInfo(int systemRuntimeMajorVersion)
        {
            SystemRuntimeMajorVersion = systemRuntimeMajorVersion;
        }

        public int SystemRuntimeMajorVersion { get; }

        public static CompilationInfo Create(Compilation compilation)
        {
            var version = compilation.ReferencedAssemblyNames.FirstOrDefault(static assemblyName => assemblyName.Name == "System.Runtime")?.Version?.Major ?? 0;
            return new CompilationInfo(version);
        }
    }

    private readonly struct GeneratorOptions
    {
        public GeneratorOptions(string targetFramework, string interceptorNamespaces)
        {
            TargetFramework = targetFramework;
            InterceptorNamespaces = interceptorNamespaces;
        }

        public string TargetFramework { get; }

        public string InterceptorNamespaces { get; }

        public static GeneratorOptions Create(AnalyzerConfigOptionsProvider provider)
        {
            provider.GlobalOptions.TryGetValue("build_property.TargetFramework", out var targetFramework);
            provider.GlobalOptions.TryGetValue("build_property.InterceptorsNamespaces", out var interceptorsNamespaces);
            provider.GlobalOptions.TryGetValue("build_property.InterceptorsPreviewNamespaces", out var previewNamespaces);
            var combinedNamespaces = string.Join(";", new[] { interceptorsNamespaces, previewNamespaces }.Where(static value => !string.IsNullOrWhiteSpace(value)));
            return new GeneratorOptions(targetFramework ?? string.Empty, combinedNamespaces);
        }

        public bool IsTargetFrameworkSupported(CompilationInfo compilationInfo)
        {
            if (TryGetTargetFrameworkMajorVersion(out var majorVersion))
            {
                return majorVersion >= 9;
            }

            return compilationInfo.SystemRuntimeMajorVersion >= 9;
        }

        public bool IsInterceptorNamespaceEnabled(string ns) =>
            InterceptorNamespaces
                .Split(new[] { ';' }, StringSplitOptions.RemoveEmptyEntries)
                .Any(value => string.Equals(value.Trim(), ns, StringComparison.Ordinal));

        private bool TryGetTargetFrameworkMajorVersion(out int majorVersion)
        {
            majorVersion = 0;
            if (string.IsNullOrWhiteSpace(TargetFramework))
            {
                return false;
            }

            var value = TargetFramework.Trim();
            if (!value.StartsWith("net", StringComparison.OrdinalIgnoreCase))
            {
                return false;
            }

            value = value.Substring(3);
            var digitsLength = 0;
            while (digitsLength < value.Length && char.IsDigit(value[digitsLength]))
            {
                digitsLength++;
            }

            return digitsLength > 0 && int.TryParse(value.Substring(0, digitsLength), NumberStyles.None, CultureInfo.InvariantCulture, out majorVersion);
        }
    }

    private readonly struct ExtensionLoggingMethodCandidate
    {
        public ExtensionLoggingMethodCandidate(
            string methodKey,
            string witnessParameterName,
            ImmutableArray<InterceptorParameter> originalMethodParameters,
            string logLevelExpression,
            string messageTemplate,
            GeneratedLogArgument? exceptionArgument,
            ImmutableArray<GeneratedLogArgument> valueArguments)
        {
            MethodKey = methodKey;
            WitnessParameterName = witnessParameterName;
            OriginalMethodParameters = originalMethodParameters;
            LogLevelExpression = logLevelExpression;
            MessageTemplate = messageTemplate;
            ExceptionArgument = exceptionArgument;
            ValueArguments = valueArguments;
        }

        public string MethodKey { get; }

        public string WitnessParameterName { get; }

        public ImmutableArray<InterceptorParameter> OriginalMethodParameters { get; }

        public string LogLevelExpression { get; }

        public string MessageTemplate { get; }

        public GeneratedLogArgument? ExceptionArgument { get; }

        public ImmutableArray<GeneratedLogArgument> ValueArguments { get; }
    }

    private readonly struct LoggedInvocation
    {
        public LoggedInvocation(
            string logLevelExpression,
            string messageTemplate,
            GeneratedLogArgument? exceptionArgument,
            ImmutableArray<GeneratedLogArgument> valueArguments)
        {
            LogLevelExpression = logLevelExpression;
            MessageTemplate = messageTemplate;
            ExceptionArgument = exceptionArgument;
            ValueArguments = valueArguments;
        }

        public string LogLevelExpression { get; }

        public string MessageTemplate { get; }

        public GeneratedLogArgument? ExceptionArgument { get; }

        public ImmutableArray<GeneratedLogArgument> ValueArguments { get; }
    }

    private readonly struct GeneratedLogArgument
    {
        public GeneratedLogArgument(string expressionText, string typeName, string parameterName)
        {
            ExpressionText = expressionText;
            TypeName = typeName;
            ParameterName = parameterName;
        }

        public string ExpressionText { get; }

        public string TypeName { get; }

        public string ParameterName { get; }
    }

    private readonly struct InterceptorParameter
    {
        public InterceptorParameter(string name, string typeName, RefKind refKind, bool isThis, bool isParams)
        {
            Name = name;
            TypeName = typeName;
            RefKind = refKind;
            IsThis = isThis;
            IsParams = isParams;
        }

        public string Name { get; }

        public string TypeName { get; }

        public RefKind RefKind { get; }

        public bool IsThis { get; }

        public bool IsParams { get; }
    }

    private readonly struct InterceptedCallSite
    {
        public InterceptedCallSite(string methodKey, int version, string data)
        {
            MethodKey = methodKey;
            Version = version;
            Data = data;
        }

        public string MethodKey { get; }

        public int Version { get; }

        public string Data { get; }
    }
}
